scopes:
  source:
    files:
      api:
        include:
          - services/api/**/*
      web:
        include:
          - apps/web/**/*

queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - label=queue-me
    merge_conditions:
      - label=allow-merge
